# Generated by Django 4.2.16 on 2024-10-31 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotegory_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vakaansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discraption', models.TextField()),
                ('time_work', models.TimeField()),
                ('time_notwork', models.TimeField()),
                ('salary', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/images')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('cotegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vakansi.cotegory')),
            ],
        ),
    ]
