# Generated by Django 4.2.16 on 2024-11-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakansi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('emal', models.EmailField(max_length=254)),
                ('discraptions', models.TextField()),
                ('resume', models.FileField(upload_to='static/files')),
            ],
        ),
    ]
