# Generated by Django 4.2.16 on 2024-11-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vakansi', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='vakansi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vakansi.vakaansi'),
        ),
    ]
